export enum BannerType {
  ADVERTISEMENT = 'ADVERTISEMENT',
  WARNING = 'WARNING',
  INFO = 'INFO',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
  ALERT = 'ALERT',
  NOTIFICATION = 'NOTIFICATION',
  PROMOTION = 'PROMOTION',
}
